---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1mldz4wftqxezaeu6gc6tflcg8ekzl93uwz7sjwlt5upjvarkx5ns3pguvx"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1mldz4wftqxezaeu6gc6tflcg8ekzl93uwz7sjwlt5upjvarkx5ns3pguvx"
