---
kubernetes:
  children:
    controllers:
      hosts:
        "k3s-node1":
          ansible_user: "sysadmin"
          ansible_host: "192.168.1.71"
        "k3s-node2":
          ansible_user: "sysadmin"
          ansible_host: "192.168.1.72"
        "k3s-node3":
          ansible_user: "sysadmin"
          ansible_host: "192.168.1.73"
