apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:Ou7YBR1sJNsEPMdggiLDixGGNz9EZRZxQt+lgABHdgs=,iv:Ihk9kZrhe5VY8CRF6/SesDp5YMlKcLsNNi1Q6Miumr0=,tag:dugr2tjhn6eJYyXBAViENw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mldz4wftqxezaeu6gc6tflcg8ekzl93uwz7sjwlt5upjvarkx5ns3pguvx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzOEtKU3NhZG50UDFsd0tF
            U2xlWUlLU0w3SkZUejZuZklIcDZVbW1YY0FJCm9LYTlNTUhQeHJlSGtNdHVodnFS
            RDlaSitDSWR5dXVhdHBFRzA4cEZNUUUKLS0tIFBIT1Voc1lEcGE2T0pQcDJOOXA2
            bmVSd3FYTmhYYTMvZ3RGdU9CYy9vVzAKWo9ri+EGLFqls9GTw+pgtAkfNmni0Gpa
            DoP5gOlDb3H3AfErg0svNcAFAOWwM39CVx7jAkIk4EquBBcWBlOhRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-08T03:36:06Z"
    mac: ENC[AES256_GCM,data:nIIvkPLcScLNmILkG/US/SF2giGerz9y4/eKOFoy1TzLTZ0ZHWjmcIeqQmV63fkMLohEZ9j5ig77seUY3tmdQmwnfXBkSgD9GcV0/3JPqjdo9j+oVe+wzFHpsc1Ueo8SPLarbuPQ619Jk9qYOSnd7uyYQ01l0oyk6/Ql+G8gZag=,iv:Q+z7ba2XMH18vT0HnjA0uQBryqA/B5MR7/UWHsKTifQ=,tag:+hiKBM5XNHGNqD9QZ2wgqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
